{
 "title": "Kubernetes Pods/Containers Resource Utilization Dashboard",
 "description": "Display usage of resources by pod or container in kubernetes cluster.",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=\"$namespace\", pod=~\"$pod\"}, container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "POD/Container CPU",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\",namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\",unit=\"core\"}) by (pod, container, namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\",namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\",unit=\"core\"}) by (pod, container, namespace)"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\", container_label_io_kubernetes_pod_namespace=~\"$namespace\", container_label_io_kubernetes_pod_name=~\"$pod\", container_label_io_kubernetes_container_name=~\"$container\",container_label_io_kubernetes_container_name!=\"POD\"}[20s])\r\n) by (container_label_io_kubernetes_pod_name, container_label_io_kubernetes_container_name)"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\", container_label_io_kubernetes_pod_namespace=~\"$namespace\", container_label_io_kubernetes_pod_name=~\"$pod\", container_label_io_kubernetes_container_name=~\"$container\",container_label_io_kubernetes_container_name!=\"POD\"}[20s])\r\n) by (container_label_io_kubernetes_pod_name, container_label_io_kubernetes_container_name)\r\n      /\r\n    sum(\r\n      container_spec_cpu_quota{image!=\"\", container_label_io_kubernetes_pod_name=~\"$pod\", container_label_io_kubernetes_container_name=~\"$container\", container_label_io_kubernetes_container_name!=\"POD\"} / container_spec_cpu_period{image!=\"\", container_label_io_kubernetes_pod_name=~\"$pod\", container_label_io_kubernetes_container_name=~\"$container\", container_label_io_kubernetes_container_name!=\"POD\"}\r\n    ) by (container_label_io_kubernetes_pod_name, container_label_io_kubernetes_container_name)\r\n\r\n"
    }
   ]
  },
  {
   "title": "POD/Container RAM",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\",namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\",unit=\"byte\"}) by (pod, container, namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\",namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\",unit=\"byte\"}) by (pod, container, namespace)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{container_label_io_kubernetes_pod_name=~\"$pod\",container_label_io_kubernetes_container_name!=\"POD\",container_label_io_kubernetes_container_name!=\"\",image!=\"\", container_label_io_kubernetes_namespace=~\"$namespace\",container_label_io_kubernetes_container_namer=~\"$container\"}) by (container_label_io_kubernetes_pod_name,container_label_io_kubernetes_container_name)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{container_label_io_kubernetes_pod_name=~\"$pod\",container_label_io_kubernetes_container_name!=\"POD\",container_label_io_kubernetes_container_name!=\"\",image!=\"\", container_label_io_kubernetes_namespace=~\"$namespace\",container_label_io_kubernetes_container_namer=~\"$container\"}) by (container_label_io_kubernetes_pod_name,container_label_io_kubernetes_container_name)/\nsum(kube_pod_container_resource_limits{resource=\"memory\",namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\",unit=\"byte\"}) by (pod, container, namespace)"
    }
   ]
  },
  {
   "title": "POD/Container CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (container_label_io_kubernetes_pod_name) (rate(container_cpu_usage_seconds_total{image!=\"\", container_label_io_kubernetes_pod_namespace=~\"$namespace\", container_label_io_kubernetes_pod_name=~\"$pod\", container_label_io_kubernetes_container_name=~\"$container\",container_label_io_kubernetes_container_name!=\"POD\"}[20s]))",
     "legendFormat": "Current: {{ container_label_io_kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "POD/Container Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{container_label_io_kubernetes_pod_name=~\"$pod\",container_label_io_kubernetes_container_name!=\"POD\",container_label_io_kubernetes_container_name!=\"\",image!=\"\", container_label_io_kubernetes_pod_namespace=~\"$namespace\",container_label_io_kubernetes_container_name=~\"$container\"}!=0",
     "legendFormat": "Current: {{ container_label_io_kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "POD/Container Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (container_label_io_kubernetes_pod_name) (rate(container_network_transmit_bytes_total{container_label_io_kubernetes_pod_name=~\"$pod\",interface=~\"eth0|ens.*\"}[20s]))",
     "legendFormat": "TX : {{ container_label_io_kubernetes_pod_name}}"
    },
    {
     "expr": "sum by (container_label_io_kubernetes_pod_name) (rate(container_network_receive_bytes_total{container_label_io_kubernetes_pod_name=~\"$pod\",interface=~\"eth0|ens.*\"}[20s]))",
     "legendFormat": "RX : {{ container_label_io_kubernetes_pod_name}}"
    }
   ]
  }
 ]
}